Add Missing Error-Handling
Current Error Handling:
`[ReferenceError: server is not defined]`

With this change:
```
ReferenceError: server is not defined
    at Object.<anonymous> (/Users/jamuferguson/dev/paypal/8ballUI/controllers/extendSession.js:26:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/jamuferguson/dev/paypal/8ballUI/node_modules/kraken-js/node_modules/express-enrouten/index.js:85:35
    at Array.forEach (native)
    at Object.withRoutes (/Users/jamuferguson/dev/paypal/8ballUI/node_modules/kraken-js/node_modules/express-enrouten/index.js:83:41)
```